CIRCUITPY_WIFI_SSID = "YOUR WiFI SSID"
CIRCUITPY_WIFI_PASSWORD = "YOUR WiFi PASSWORD"
PICO_IP_ADDRESS = "192.168.xxx.xxx"
PICO_NET_MASK = "255.255.255.0"
PICO_GATEWAY = "192.168.xxx.1"
PICO_WEB_PORT = "YOUR PORT NUMBER"
